// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var Todo$Nonsense = require("./Todo.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Todo$Nonsense.make, {}), "root");

/*  Not a pure module */
