// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var Counter$Nonsense = require("./Counter.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Counter$Nonsense.make, {}), "root");

/*  Not a pure module */
